### ISSUE TITLE
Blank response returned

### ISSUE THREAD

**Issue by justanothernoob4648** [ErikBoesen/schoolopy#19]
Using get_courses, and looking at the code, it seems I keep getting the decode error in the try except block
sc = schoolopy.Schoology(schoolopy.Auth(
        'XXXXXXXX', 'XXXXXXXXXXXXXXXXXX'))
response = sc.get_courses()
print(response)
I get simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ErikBoesen** [comment]
This seems to be an issue on Schoology's side. Unfortunately I can't do much about this. Sorry.
