### ISSUE TITLE
How do I use the schoolopy_models_Grade object?

### ISSUE THREAD

**Issue by JustAnOkapi** [ErikBoesen/schoolopy#22]
What is the correct way to use the schoolopy_models_Grade objects you get from sc.get_user_grades()? @ErikBoesen

**Comment by ErikBoesen** [comment]
Not sure what you mean. These objects should function just like any of the other models in this package. Get properties of the object with `Grade.propname`.

**Comment by JustAnOkapi** [comment]
> Not sure what you mean. These objects should function just like any of the other models in this package. Get properties of the object with `Grade.propname`.

where do i find all of the propriety names

**Comment by ErikBoesen** [comment]
Here it is on Schoology's official documentation: https://developers.schoology.com/api-documentation/rest-api-v1/grade
