### ISSUE TITLE
Not on PyPI

### ISSUE THREAD

**Issue by Armdug20** [ErikBoesen/schoolopy#3]
When is this available on pip?

**Comment by ErikBoesen** [comment]
This is something we're planning to do when the library is in a more complete state. We still have to figure out three-legged auth (#2), check the code for any remaining typos and semantic errors, etc.

If you need it now, you can clone the repository and run
```sh
pip3 install -e /path/to/directory
```

**Comment by ErikBoesen** [comment]
The package, being in a usable state, is now available from PyPI as `schoolopy`.
