### ISSUE TITLE
OAuth Request Not working when creating a schoology app

### ISSUE THREAD

**Issue by jwizenfeld04** [ErikBoesen/schoolopy#35]
I created a schoology app in my school in schoology and it provides oauth info. When I use the consumer key and secret it works on the initial authentication for the three legged login but when I save the access tokens and run the authentication again it runs but the api requests don’t go through and I get no data. Do I need to add anything in the authentication to make it work.

**Comment by AndrewLester** [comment]
Try taking a look at this reply to an old issue:
https://github.com/ErikBoesen/schoolopy/issues/24#issuecomment-769254460
With a focus on this line:
```python
auth2.oauth.token = {'oauth_token': tok, 'oauth_token_secret': sec}
```

Essentially, you need to manually update the Auth instance's auth object with your saved token and secret.

If this doesn't work still please send another reply, I haven't tested the API in a Schoology App environment, so I'm not familiar with how authentication works there.

**Comment by jwizenfeld04** [comment]
That seemed to fix the issue for now. Can you explain what the line does though and why it’s needed if you are already setting the access token  and secret in the Schoology.Auth instance.

**Comment by AndrewLester** [comment]
> That seemed to fix the issue for now. Can you explain what the line does though and why it’s needed if you are already setting the access token and secret in the Schoology.Auth instance.

Good to hear! The line just lets the internal `oauth`object, which actually uses the token and secret, know about the passed in token and secret. Unfortunately the constructor doesn't do that at the moment. A change for this would be very welcome, it may just be sticking that line in the constructor or passing in the token to the `oauth` object initialization.
