### ISSUE TITLE
"Unable to launch app, there was no valid return URL found."

### ISSUE THREAD

**Issue by JaredTauler** [ErikBoesen/schoolopy#44]
Using 3 legged oauth, I keep getting the error message: "Unable to launch app, there was no valid return URL found." after authorizing.
I'm mystified as to why I'm getting this error message, as my little program was working completely fine one day, and the next day I start getting this error. 
Schoology hates mycallback no matter what url I give it. I was using localhost:5000 initially, but not even things like google.com are working. I've tried adding http://, https://, adding a slash to the end, nothing works. 2 legged authentication does work however, and when I don't specify a callback url I don't get an error either. 
To make matters worse, the example 3 legged comes up with the same error.
I checked the Schoology account to see if maybe I got rate limited or something but I didn't see anything out of the ordinary. I've tried using a computer that wasn't behind a firewall as a last ditch effort. 
Sorry if this isn't the right place for this but I've been messing with this for a few days now and I literally don't know what to do.

**Comment by JaredTauler** [comment]
I think I might have gotten rate limited or something because I tried running my code today and it worked perfectly like before. Sorry I'm stupid and I made a thread about this.

**Comment by ErikBoesen** [comment]
Hey no worries Jared! Thanks for using schoolopy and do reach out with any further questions.
