### ISSUE TITLE
get_sections method

### ISSUE THREAD

**Issue by hdadhich01** [ErikBoesen/schoolopy#45]
Using the `get_sections` method with a schoolopy authenticated object renders a forbidden URL client error.
```
File "/home/runner/Test-1/venv/lib/python3.8/site-packages/schoolopy/main.py", line 283, in get_sections
    return [Section(raw) for raw in self._get('sections')['section']]
  File "/home/runner/Test-1/venv/lib/python3.8/site-packages/schoolopy/main.py", line 39, in _get
    response.raise_for_status()
  File "/home/runner/Test-1/venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.schoology.com/v1/sections?limit=1
```

**Comment by ErikBoesen** [comment]
Are you able to make requests to other endpoints without getting 403s?

**Comment by hdadhich01** [comment]
Yes.

**Comment by CoderN-P** [comment]
This can happen if the API Key and Secret you used for authorization is **NOT** from your Schoology organization. For example, if you use an API Key & Secret made from another school then it won't work for fetching this data in your school. To generate an API key/secret go to `{your schoology link}/api`
