### ISSUE TITLE
create_user method

### ISSUE THREAD

**Issue by rmduddy** [ErikBoesen/schoolopy#5]
Hey there, great bit of work here!  I'm probably an idiot and this is not the right place to ask but I'm having some issues passing the user values to the create_user method.  I know that it's expecting a JSON object with the required attributes for a user as specified in the API documentation.  I was trying either a converted python object using json.dumps or passing a straight dictionary (I'm new to APIs).  Any chance you could show me a usage example?
Thanks a bunch!

**Comment by ErikBoesen** [comment]
Happy to help out! Glad to see someone other than I making use of this library.

Rather than passing a JSON object or dictionary, you should pass an actual `User` object. What you can do here is to instantiate an object (it'd be easiest to pass it a dictionary with your desired properties), then pass that to the function.

Here's a simple use case:
```py
user = schoolopy.User({
    # Include necessary data according to API documentation, as you apparently have already done
})
api.create_user([other parameters], user)
```
Please let me know if you have any further questions!

**Comment by rmduddy** [comment]
I feel dumb ha.  That makes perfect sense, thanks so much for your response!

**Comment by ErikBoesen** [comment]
No problem! Let me know if you need anything or come across any issues with this library.

**Comment by rmduddy** [comment]
I figured it out, the first way I was passing would have worked and then I went down the rabbit hole trying to figure it out.  The actual issue was the user_id parameter of that method was leading to an invalid endpoint.  

I forked the project and submitted a pull request with a fix (I hope this is proper etiquette, and that I actually did submit the pull request... I'm also new to github).   And although being new to APIs and github and occasionally not being able to wrap my head around some object oriented stuff I'm normally a pretty quick study, and have a good working knowledge of Schoology.  I plan on continuing to use and contributing more when I am able.  Again awesome work so far, and thanks for the excellent communication!

**Comment by ErikBoesen** [comment]
Yeah, your contribution was perfectly idiomatic. I would never have guessed you're new to this. You even titled your commit in the imperative tense, which almost nobody does correctly. I'm glad to hear you'll be helping contribute further! I'm excited to work with you! 😃
