### ISSUE TITLE
start parameter not pulled into api call

### ISSUE THREAD

**Issue by samterfa** [ErikBoesen/schoolopy#56]
I've created a [PR](https://github.com/ErikBoesen/schoolopy/pull/55) for this. Hopefully it's reasonable. start and limit are parameters for list api calls. The Schoology class passes limit to the api call via the _get_params_string function, but not the start parameter. That makes pagination tough to navigate.

**Comment by ErikBoesen** [comment]
Thanks so much for your contribution!

**Comment by ErikBoesen** [comment]
Just released v3.2.2 to finalize this patch.
